### ISSUE TITLE
error: file-permissions-check failed: executable should be in tools/ directory: main.sh

### ISSUE THREAD

**Issue by jayvdb** [taiki-e/install-action#302]
https://github.com/taiki-e/install-action/actions/runs/7154757157/job/19482642672?pr=299 failed with

```
info: checking file permissions
Error: file-permissions-check failed: executable should be in tools/ directory
=======================================
main.sh
=======================================
```

I can reproduce this locally

**Comment by taiki-e** [comment]
You need to add publish=false, if you add version to manifest. 

Note that both version and publish were removed in the commit that adopted the version-less manifest (https://github.com/taiki-e/install-action/commit/88c52281ad0c02e9c2f84ca76b7c589db5d7a9e7). If you are re-adding a version, please revert that commit rather than manually adding the fields.
