### ISSUE TITLE
Use unpublished version of 'cross' as latest versions

### ISSUE THREAD

**Issue by pvshvp-oss** [taiki-e/install-action#405]
At the time of writing this, the apparent "latest" GitHub releases of `cross` are not the current versions at all. They are backports. They use Ubuntu 16.04, which is so outdated that many packages do not exist there. Please refer to https://github.com/cross-rs/cross/issues/517#issuecomment-1500689545.

**Comment by taiki-e** [comment]
I suppose it is theoretically possible to disguise an arbitrary commit that has not been published in cross as if it were a specific release, but it would confuse users due to differences in locally installed versions using cargo install or cargo install.

And, of course, none of the commits since 0.2.5 have been published, so they could also contain arbitrary breaking changes.

The best solution here is to help cross development so that a new version can be published, and until then use the workaround as described in the cross wiki.  The workaround here is also useful for local use of cross.
